---
machines:
  foo:
    devices:
    - vendor-id: 0x046d
      product-id: 0xc08e
    - vendor-id: 0x3434
      product-id: 0x0211
  bar:
    devices:
    - vendor-id: 0x07fd
      product-id: 0x0008
