---
machines:
  foo:
    devices:
    - vendor-id: 0x12d1
      product-id: 0x1f01
    - vendor-id: 0x12d1
      product-id: 0x1442
  bar:
    devices:
    - udev:
        env:
        - name: ID_VENDOR
          equals: ftdi
        - name: ID_MODEL
          equals: usb_serial_converter
        - name: ID_SERIAL_SHORT
          equals: ftIdOOt7
  video:
    devices:
    - vendor-id: 0x046d
      product-id: 0x0825
      udev:
        env:
        - name: ID_USB_SERIAL_SHORT
          pattern: '^3187B6[01]$'
  blub:
    devices:
    - vendor-id: 0x046d
      product-id: 0x0825
      udev:
        tags:
        - some-tag
